# ios.yml 
# base code from https://github.com/jaredtao/HelloActions-Qt

name: IOS
on: 
  push:
    paths-ignore:
      - 'Example.md'
      - 'HowToSetProject.ko.md'
      - 'HowToSetProject.md'
      - 'README.ko.md'
      - 'README.md'
      - 'TestEnv.md'
      - 'ToTest.md'
      - 'ToUpgrade.md'
      - 'Vision.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'Example.md'
      - 'HowToSetProject.ko.md'
      - 'HowToSetProject.md'
      - 'README.ko.md'
      - 'README.md'
      - 'TestEnv.md'
      - 'ToTest.md'
      - 'ToUpgrade.md'
      - 'Vision.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [5.12.6]
        qt_target: [ios]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ios
        run: |
          cd HelloAndroid
          qmake -r -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos
          make
